### ISSUE TITLE
Reconnection when server reboots

### ISSUE THREAD

**Issue by rickyshrestha** [utilitywarehouse/go-pubsub#38]
When the underlying nats connection is closed when using nats-streaming, the subscription is not notified. When checking the underlying nats connection, it seems it does re-connect but the subscriptions do not receive any messages even after re-connecting. 

When the connection to the server is lost, error should be thrown for the consumer application to handle.

**Comment by mjgarton** [comment]
Are you talking about the connection between the client and nats, or between nats-streaming and nats?

**Comment by mjgarton** [comment]
.. and can you reproduce this easily?

**Comment by rickyshrestha** [comment]
yes this can be reproduced easily by creating a consumer connection, restarting the docker container running nats. The consumer stays up but any new msgs are not received by the consumer. I can show this if you'd like

**Comment by rickyshrestha** [comment]
demo of this issue can be found at https://github.com/utilitywarehouse/go-pubsub-issue-38-demo
