### ISSUE TITLE
Insist on an Envelope?

### ISSUE THREAD

**Issue by JamieAP** [utilitywarehouse/go-pubsub#66]
Our current interface of []byte allows a producer to produce any payload it wants. It may be desirable to insist on a common `Envelope` type for all users of pubsub to provide a baseline of consistency. 

Alternatively this could happen transparently, keeping the interface as []byte but wrapping produced payloads in a common type.

**Comment by mjgarton** [comment]
I think this belongs at a later above the whole of go-pubsub, so ,while it would be useful and interesting to see this implemented, I think it's out of scope for go-pubsub, so I'm going to close this.
